### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by ezazwar1** [dev4living/HeyCommunity#11]
Hey I am unable to register can you please provide me with a fake username and password

Regards 
Ezaz

**Comment by supgeek-rod** [comment]
You can use 
phone: 12312341234
password: admin1234
on http://demo.hey-community.cn

The software is development, have fun 
Please do not abuse

**Comment by ezazwar1** [comment]
Thanks
@supgeek-rod

**Comment by ezazwar1** [comment]
i suggest using some loader like in Instagram that will show up while the Image is Loading

**Comment by supgeek-rod** [comment]
Yes, it's on the dev list

**Comment by ezazwar1** [comment]
Great Do you have some Directive which will show up while loading like instagram i am currently using 
spinkit 

Regards
ezaz

**Comment by supgeek-rod** [comment]
https://github.com/Urigo/angular-spinkit is amazing
