### ISSUE TITLE
关于 git submodule update 缓慢问题的解决办法

### ISSUE THREAD

**Issue by supgeek-rod** [dev4living/HeyCommunity#42]
中国大陆用户可能执行 `git submodule update` 去下载项目依赖的模块时，速度非常慢
不是是否有用户关心这个问题

**Comment by steven1227** [comment]
翻墙。。。

**Comment by supgeek-rod** [comment]
发布新版本的时候释出完整的软件源代码，以解决 github 速度缓慢的问题。
