### ISSUE TITLE
(500 Internal Server Error for URL: http://localhost:8100/api/timeline)  #dev4living/HeyCommunity

### ISSUE THREAD

**Issue by Theos17** [dev4living/HeyCommunity#53]
I am trying to run a dev4living/HeyCommunity  webApp on a local host but i'm getting the following error:
Error: connect EADDRINUSE 127.0.0.1:8100
   at Object.exports._errnoException (util.js:1022:11)
   at exports._exceptionWithHostPort (util.js:1045:20)
   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

![12](https://cloud.githubusercontent.com/assets/26035431/23337464/a141c53a-fc29-11e6-9bed-6e69e2ff1c2d.png)
![13](https://cloud.githubusercontent.com/assets/26035431/23337465/a67e2804-fc29-11e6-927c-64e6566125e7.png)
![14](https://cloud.githubusercontent.com/assets/26035431/23337467/aad2afa6-fc29-11e6-9f78-30319685299c.png)
![15](https://cloud.githubusercontent.com/assets/26035431/23337482/178de82c-fc2a-11e6-9751-66ffe33ac948.png)
![16](https://cloud.githubusercontent.com/assets/26035431/23337483/1b2ac306-fc2a-11e6-801e-24e682e849d4.png)
i used the lastest update dev-playing  : dev4living/HeyCommunity-backend  and dev4living/HeyCommunity-frontend

 What should i  do to fix this error?
Your assistance will be very much appreciated.

**Comment by supgeek-rod** [comment]
You WebApp through `ionic serve`，you may need to define the `window.API_DOMAIN`
`ionic.config.json` `proxies` define the proxy. 

```
"path": "/api",
"proxyUrl": "http://demo.hey-community.com/api",
```

It's meets, you access `http://localhost:8100/api` (your window.localhost.host) equal to access `http://demo.hey-community.com`

So your `proxyUrl`should not be `http://localhost:8100/api`，You need to deploy the backend and fill in the correct `proxyUrl`, like `http://demo.hey-community.com/api`

Forgive me bad English

**Comment by supgeek-rod** [comment]
Please update to https://github.com/dev4living/HeyCommunity/tree/v3.0.0-beta.4

**Comment by Theos17** [comment]
okay, thanks !
lets me try them .
by the way , your English is good !
