### ISSUE TITLE
用户的关注和 block 功能

### ISSUE THREAD

**Issue by supgeek-rod** [dev4living/HeyCommunity#61]
现在要增加关注用户和 block 用户功能，一个用户可关注多个用户。一个用户可以 block 多个用户。

数据和功能设计:
- 一张用户关系表，记录 type (关系类型) 和  user (用户) 以及 relate_user (关联的用户)

**Comment by ety001** [comment]
type(关系类型)是指什么没有弄明白，预留下这个字段了，字段类型为integer
user_relationship
  - id
  - type
  - from_user_id
  - to_user_id
  - is_block
  - deleted_at
  - created_at
  - updated_at

**Comment by supgeek-rod** [comment]
type (关系类型）为粉丝、朋友或黑名单呀，那就不需要 is_block 字段了

**Comment by ety001** [comment]
粉丝不就是单向关注，朋友不就是双向关注？
我现在的这个数据结构就足够了。
