### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by ghost** [dev4living/HeyCommunity#65]
Hi there,

is there an english version of frontend and backend? Would like to test it

**Comment by mad2kx** [comment]
Hi. Yes this one. I would like to work with you guys on an English version. How can I contribute?

**Comment by supgeek-rod** [comment]
@mad2kx you need to fork the project first and then do some i18n work, finally create new pull request to merge your work into the project

but first you need to know laravel framework, if you know please add my skype zhanghooyo@outlook.com or my WeChat 17600719763

**Comment by mad2kx** [comment]
Hi @supgeek-rod ,

I have heard of Laravel and did some research on it but not 100% familar with it. Let me start forking the project first?

**Comment by supgeek-rod** [comment]
do it ~

**Comment by supgeek-rod** [comment]
do it ~
