### ISSUE TITLE
git submodule update --init --recursive --depth 1失败

### ISSUE THREAD

**Issue by YuiZhang** [dev4living/HeyCommunity#66]
系统是ubuntu 12.04

administrator@ubuntu:/home/HeyCommunity$ sudo git submodule update --init --recursive --depth 1
Usage: git submodule [--quiet] add [-b branch] [-f|--force] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] update [--init] [-N|--no-fetch] [-f|--force] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--] [<path>...]

**Comment by supgeek-rod** [comment]
请给出报错信息，才能定位问题
你也可以直接从 releases 中下载释出的源代码，另外 v3 已经停止维护了，请关注  https://github.com/dev4living/HeyCommunity-web
