### ISSUE TITLE
problem when run the project

### ISSUE THREAD

**Issue by koolstens** [dev4living/HeyCommunity#70]
Hi,

I download the frontend version of the project and use this commands to run it 

1- run ionic state restore
2- run npm install
3-run ionic serve

after runing ionic serve i get a blank page

Can you help me please?
Thank you so much

npm --version
5.6.0
ionic --version
4.10.2

**Comment by donmarcos** [comment]
what is your Ionic version ?

**Comment by supgeek-rod** [comment]
HeyCommunity V3 has been abandoned, no longer developed and supported.
You can get the latest ionic app code https://github.com/dev4living/HeyCommunity-frontend

Build process if there is a problem, please check terminal console log and web browser console log
